import { ServiceProvider, ServiceCategory } from "./types";

export const SWISS_KANTONS = [
  "Zürich",
  "Bern",
  "Luzern",
  "Uri",
  "Schwyz",
  "Obwalden",
  "Nidwalden",
  "Glarus",
  "Zug",
  "Fribourg",
  "Solothurn",
  "Basel-Stadt",
  "Basel-Landschaft",
  "Schaffhausen",
  "Appenzell Ausserrhoden",
  "Appenzell Innerrhoden",
  "St. Gallen",
  "Graubünden",
  "Aargau",
  "Thurgau",
  "Ticino",
  "Vaud",
  "Valais",
  "Neuchâtel",
  "Geneva",
  "Jura",
];

export const mockServices: ServiceProvider[] = [
  {
    id: "service-1",
    name: "МайстерОК",
    category: "Домашній майстер",
    address: "Bahnhofstrasse 10",
    kanton: "Zürich",
    zipCode: "8001",
    instagram: "https://instagram.com/maysterok",
    website: "https://maysterok.ch",
    services: [
      "Дрібний ремонт",
      "Складання меблів",
      "Електричні роботи",
      "Сантехнічні роботи",
    ],
    online: false,
    offline: true,
    phone: "+41 76 123 45 67",
    email: "info@maysterok.ch",
    views: 128,
    description:
      "Надаємо широкий спектр послуг з домашнього ремонту. Працюємо швидко та якісно. Наші майстри мають багаторічний досвід.",
  },
  {
    id: "service-2",
    name: "IT Solutions",
    category: "IT Розробка",
    address: "Langstrasse 45",
    kanton: "Zürich",
    zipCode: "8004",
    website: "https://uait.solutions",
    services: [
      "Розробка веб-сайтів",
      "Мобільні додатки",
      "Підтримка IT інфраструктури",
      "WordPress",
      "Shopify",
    ],
    online: true,
    offline: true,
    phone: "+41 76 987 65 43",
    email: "info@uait.solutions",
    views: 245,
    description:
      "Професійна розробка сайтів та мобільних додатків для бізнесу. Працюємо з клієнтами по всій Швейцарії. Створюємо сучасні, швидкі та зручні веб-сайти.",
  },
  {
    id: "service-3",
    name: "CleanHome",
    category: "Клінінгові послуги",
    address: "Seestrasse 120",
    kanton: "Luzern",
    zipCode: "6004",
    instagram: "https://instagram.com/cleanhome_ch",
    services: [
      "Прибирання квартир",
      "Миття вікон",
      "Прибирання офісів",
      "Хімчистка меблів",
    ],
    online: false,
    offline: true,
    email: "info@cleanhome.ch",
    views: 187,
    description:
      "Прибирання квартир та офісів на найвищому рівні. Використовуємо професійне обладнання та екологічні засоби для чищення.",
  },
  {
    id: "service-4",
    name: "Swiss Beauty",
    category: "Послуги краси",
    address: "Rue du Mont-Blanc 16",
    kanton: "Geneva",
    zipCode: "1201",
    instagram: "https://instagram.com/swiss_beauty",
    website: "https://swiss-beauty.ch",
    services: [
      "Манікюр",
      "Педикюр",
      "Нарощування вій",
      "Фарбування брів",
      "Макіяж",
    ],
    online: false,
    offline: true,
    phone: "+41 78 456 78 90",
    email: "info@swiss-beauty.ch",
    views: 312,
    description:
      "Салон краси в центрі Женеви. Майстри з України. Використовуємо якісні матеріали та інструменти. Працюємо за попереднім записом.",
  },
  {
    id: "service-5",
    name: "UkrAuto",
    category: "Авто",
    address: "Industriestrasse 30",
    kanton: "Aargau",
    zipCode: "5000",
    website: "https://ukrauto.ch",
    services: [
      "Ремонт автомобілів",
      "Заміна масла",
      "Діагностика",
      "Шиномонтаж",
    ],
    online: false,
    offline: true,
    phone: "+41 79 123 78 90",
    email: "service@ukrauto.ch",
    views: 156,
    description:
      "Автосервіс з українськими майстрами. Обслуговуємо всі марки автомобілів. Справедливі ціни та висока якість роботи.",
  },
  {
    id: "service-6",
    name: "DesignUA",
    category: "Дизайн",
    address: "Online",
    kanton: "Zürich",
    zipCode: "8002",
    instagram: "https://instagram.com/designua_ch",
    website: "https://designua.ch",
    services: [
      "Графічний дизайн",
      "Дизайн логотипів",
      "Брендинг",
      "Дизайн сайтів",
      "UI/UX",
    ],
    online: true,
    offline: false,
    phone: "+41 76 111 22 33",
    email: "hello@designua.ch",
    views: 289,
    description:
      "Графічний дизайн будь-якої складності. Розробка логотипів, брендинг, дизайн сайтів та поліграфії. Допоможемо виділитися серед конкурентів.",
  },
  {
    id: "service-7",
    name: "UkrTutor",
    category: "Репетитори",
    address: "Bahnhofplatz 5",
    kanton: "Bern",
    zipCode: "3011",
    instagram: "https://instagram.com/ukrtutor_ch",
    services: [
      "Математика",
      "Фізика",
      "Німецька мова",
      "Англійська мова",
      "Українська мова",
    ],
    online: true,
    offline: true,
    phone: "+41 78 222 33 44",
    email: "info@ukrtutor.ch",
    views: 175,
    description:
      "Репетитори з України. Підготовка до екзаменів, допомога зі складними предметами. Індивідуальний підхід до кожного учня.",
  },
  {
    id: "service-8",
    name: "Смачного",
    category: "Гастрономія",
    address: "Schwanengasse 3",
    kanton: "Basel-Stadt",
    zipCode: "4051",
    instagram: "https://instagram.com/smachnogo_ch",
    website: "https://smachnogo.ch",
    services: ["Домашня кухня", "Випічка", "Торти на замовлення", "Кейтеринг"],
    online: true,
    offline: true,
    phone: "+41 79 333 44 55",
    email: "zamovlennya@smachnogo.ch",
    views: 267,
    description:
      "Смачні страви української кухні, домашня випічка, торти на замовлення. Доставка по місту або самовивіз.",
  },
];
