import { CommunityMember } from "./types";

export const mockCommunityMembers: CommunityMember[] = [
  {
    id: "1",
    firstName: "Олена",
    lastName: "Кравченко",
    avatarUrl: "https://randomuser.me/api/portraits/women/1.jpg",
    kanton: "ZH",
    interests: ["хайкінг", "фотографія", "плавання"],
    contacts: {
      telegram: "https://t.me/olena_kravchenko",
      instagram: "https://instagram.com/olena_photos",
    },
    bio: "Переїхала до Швейцарії у 2022 році. Люблю досліджувати гірські маршрути та ділитися фотографіями.",
    joinedAt: "2023-03-15",
    isVerified: true,
  },
  {
    id: "2",
    firstName: "Максим",
    lastName: "Ковальчук",
    avatarUrl: "https://randomuser.me/api/portraits/men/2.jpg",
    kanton: "BE",
    interests: ["IT", "спорт", "музика", "кіно"],
    contacts: {
      whatsapp: "https://wa.me/41791234567",
      facebook: "https://facebook.com/max.kovalchuk",
    },
    bio: "Розробник програмного забезпечення. Вільний час проводжу активно: біг, плавання, велосипед.",
    joinedAt: "2023-01-10",
    isVerified: true,
  },
  {
    id: "3",
    firstName: "Ірина",
    nickname: "Iruska",
    avatarUrl: "https://randomuser.me/api/portraits/women/3.jpg",
    kanton: "GE",
    interests: ["малювання", "вишивка", "рукоділля"],
    contacts: {
      instagram: "https://instagram.com/iryna_art",
      viber: "viber://chat?number=+41761234567",
    },
    bio: "Художниця та майстриня. Проводжу онлайн-майстеркласи з вишивки.",
    joinedAt: "2023-05-20",
    isVerified: false,
  },
  {
    id: "4",
    firstName: "Андрій",
    lastName: "Шевченко",
    avatarUrl: "https://randomuser.me/api/portraits/men/4.jpg",
    kanton: "LU",
    interests: ["спорт", "подорожі", "IT"],
    contacts: {
      telegram: "https://t.me/andrii_travel",
      whatsapp: "https://wa.me/41762345678",
    },
    bio: "Любитель активного відпочинку та технологій. Працюю в IT компанії у Люцерні.",
    joinedAt: "2022-11-05",
    isVerified: true,
  },
  {
    id: "5",
    firstName: "Наталія",
    lastName: "Мельник",
    avatarUrl: "https://randomuser.me/api/portraits/women/5.jpg",
    kanton: "BS",
    interests: ["спів", "танці", "музика"],
    contacts: {
      instagram: "https://instagram.com/nataliya_music",
      facebook: "https://facebook.com/nataliya.melnyk",
    },
    bio: "Професійна вокалістка. Організовую українські культурні заходи в Базелі.",
    joinedAt: "2023-02-14",
    isVerified: false,
  },
  {
    id: "6",
    firstName: "Віктор",
    lastName: "Петренко",
    avatarUrl: "https://randomuser.me/api/portraits/men/6.jpg",
    kanton: "VD",
    interests: ["хайкінг", "фотографія", "подорожі", "волонтерство"],
    contacts: {
      telegram: "https://t.me/viktor_swiss",
      whatsapp: "https://wa.me/41763456789",
    },
    bio: "Люблю подорожувати Швейцарією та сусідніми країнами. Активно допомагаю новоприбулим українцям.",
    joinedAt: "2022-09-30",
    isVerified: true,
  },
  {
    id: "7",
    firstName: "Марія",
    lastName: "Іваненко",
    avatarUrl: "https://randomuser.me/api/portraits/women/7.jpg",
    kanton: "ZH",
    interests: ["гастрономія", "садівництво", "читання"],
    contacts: {
      instagram: "https://instagram.com/maria_cook",
      viber: "viber://chat?number=+41764567890",
    },
    bio: "Кулінар і блогер. Ділюся рецептами українських страв, адаптованих до швейцарських інгредієнтів.",
    joinedAt: "2023-04-08",
    isVerified: false,
  },
  {
    id: "8",
    firstName: "Сергій",
    nickname: "Serg_Swiss",
    avatarUrl: "https://randomuser.me/api/portraits/men/8.jpg",
    kanton: "TI",
    interests: ["IT", "плавання", "йога", "кіно"],
    contacts: {
      telegram: "https://t.me/serg_swiss",
      facebook: "https://facebook.com/sergiy.swiss",
    },
    bio: "Працюю віддалено в IT сфері. Насолоджуюсь життям у сонячному Тічино.",
    joinedAt: "2022-12-20",
    isVerified: true,
  },
];
