export const COUNTRIES = [
  { value: "ukraine", label: "Україна" },
  { value: "switzerland", label: "Швейцарія" },
  { value: "germany", label: "Німеччина" },
  { value: "france", label: "Франція" },
  { value: "italy", label: "Італія" },
  { value: "austria", label: "Австрія" },
  { value: "poland", label: "Польща" },
  { value: "slovakia", label: "Словаччина" },
  { value: "hungary", label: "Угорщина" },
  { value: "romania", label: "Румунія" },
  { value: "moldova", label: "Молдова" },
  { value: "belarus", label: "Білорусь" },
  { value: "russia", label: "Росія" },
  { value: "other", label: "Інша" },
];

export const CANTONS = [
  { value: "ZH", label: "Zürich" },
  { value: "BE", label: "Bern" },
  { value: "LU", label: "Lucerne" },
  { value: "UR", label: "Uri" },
  { value: "SZ", label: "Schwyz" },
  { value: "OW", label: "Obwalden" },
  { value: "NW", label: "Nidwalden" },
  { value: "GL", label: "Glarus" },
  { value: "ZG", label: "Zug" },
  { value: "FR", label: "Fribourg" },
  { value: "SO", label: "Solothurn" },
  { value: "BS", label: "Basel-Stadt" },
  { value: "BL", label: "Basel-Landschaft" },
  { value: "SH", label: "Schaffhausen" },
  { value: "AR", label: "Appenzell Ausserrhoden" },
  { value: "AI", label: "Appenzell Innerrhoden" },
  { value: "SG", label: "St. Gallen" },
  { value: "GR", label: "Graubünden" },
  { value: "AG", label: "Aargau" },
  { value: "TG", label: "Thurgau" },
  { value: "TI", label: "Ticino" },
  { value: "VD", label: "Vaud" },
  { value: "VS", label: "Valais" },
  { value: "NE", label: "Neuchâtel" },
  { value: "GE", label: "Geneva" },
  { value: "JU", label: "Jura" },
];

export const SWISS_STATUSES = [
  { value: "S", label: "S - Швейцарський резидент" },
  { value: "L", label: "L - Дозвіл на проживання" },
  { value: "B", label: "B - Дозвіл на проживання" },
  { value: "C", label: "C - Постійний дозвіл на проживання" },
  { value: "F", label: "F - Дозвіл на проживання для біженців" },
  { value: "N", label: "інше" },
];
