export const COUNTRIES = [
  { code: "ukraine", name: "Україна" },
  { code: "switzerland", name: "Швейцарія" },
  { code: "germany", name: "Німеччина" },
  { code: "france", name: "Франція" },
  { code: "italy", name: "Італія" },
  { code: "austria", name: "Австрія" },
  { code: "poland", name: "Польща" },
  { code: "slovakia", name: "Словаччина" },
  { code: "hungary", name: "Угорщина" },
  { code: "romania", name: "Румунія" },
  { code: "moldova", name: "Молдова" },
  { code: "belarus", name: "Білорусь" },
  { code: "russia", name: "Росія" },
  { code: "other", name: "Інша" },
];

export const CANTONS = [
  { code: "ZH", name: "Zürich" },
  { code: "BE", name: "Bern" },
  { code: "LU", name: "Lucerne" },
  { code: "UR", name: "Uri" },
  { code: "SZ", name: "Schwyz" },
  { code: "OW", name: "Obwalden" },
  { code: "NW", name: "Nidwalden" },
  { code: "GL", name: "Glarus" },
  { code: "ZG", name: "Zug" },
  { code: "FR", name: "Fribourg" },
  { code: "SO", name: "Solothurn" },
  { code: "BS", name: "Basel-Stadt" },
  { code: "BL", name: "Basel-Landschaft" },
  { code: "SH", name: "Schaffhausen" },
  { code: "AR", name: "Appenzell Ausserrhoden" },
  { code: "AI", name: "Appenzell Innerrhoden" },
  { code: "SG", name: "St. Gallen" },
  { code: "GR", name: "Graubünden" },
  { code: "AG", name: "Aargau" },
  { code: "TG", name: "Thurgau" },
  { code: "TI", name: "Ticino" },
  { code: "VD", name: "Vaud" },
  { code: "VS", name: "Valais" },
  { code: "NE", name: "Neuchâtel" },
  { code: "GE", name: "Geneva" },
  { code: "JU", name: "Jura" },
];

export const SWISS_STATUSES = [
  { code: "S", name: "S - Швейцарський резидент" },
  { code: "L", name: "L - Дозвіл на проживання" },
  { code: "B", name: "B - Дозвіл на проживання" },
  { code: "C", name: "C - Постійний дозвіл на проживання" },
  { code: "F", name: "F - Дозвіл на проживання для біженців" },
  { code: "N", name: "інше" },
];
